### ISSUE TITLE
Differences among outputted BAM files

### ISSUE THREAD

**Issue by fansalon** [nixonlab/stellarscope#22]
Hi,

thanks for developing such a nice tool!

I am running stellarscope with the ```--updated_sam``` option and I have a question regarding the generated BAM files.

According to your documentation the "other.bam" file contains the alignments that overlap the TE annotation, while "tmp_tele.bam" contains the alignments that do not overlap the TE annotation.

"First, pbmc500_individual-other.bam, pbmc500_individual-tmp_tele.bam, and pbmc500_individual-checkpoint.load_alignment.pickle are generated. These BAM files contain the alignments that do and do not overlap the TE annotation, respectively".

Am I wrong in thinking it is actually the opposite?

Also, which is the difference between the "tmp_tele.bam" and "-updated.bam" files?

At a first look, it seems the two file contains the same alignments in terms of reads and coordinates, but the "-updated.bam" contains some additional tags and some other tags (*i.e.* ,MAPQ and flag) differ from the "tele.bam".

 If my interpretation is correct, why the same alignments have different MAPQ and flags in the two bam files?

Thanks in advance,
Federico

**Comment by mlbendall** [comment]
Dear Federico,
Thanks for trying out our tool!

To your first point, the documentation is indeed reversed - `other.bam` contains alignments that DO NOT overlap the annotation, and `tmp_tele.bam` contains alignments that DO overlap the annotation. More precisely, for each fragment (read or read pair), if one or more of the possible alignments overlaps with the TE annotation, all alignments for that fragment are written to `tmp_tele.bam`. Otherwise, when none of the fragments alignments overlap with the TE annotation, all the alignments for that fragment are written to `other.bam`. Thus, there are alignments that do not overlap with the annotation in `tmp_tele.bam`, but only when another possible alignment for the fragment does overlap with the TE annotation.

Some useful properties:

- Concatenating `tmp_tele.bam` and `other.bam` will give you your original BAM file, though not necessarily in the same order.
- Reads that are in `tmp_tele.bam` are not found in `other.bam` and vice versa.

`tmp_tele.bam` is intended to be a temporary/intermediate file and is not necessarily a final output. It contains the alignments exactly as they appear in the original BAM. (We use it so that alignments don't need to be stored in memory, and it is read from disk when creating the updated BAM is created.)

Which gets at your second question, the differences between `tmp_tele.bam` and `updated.bam`.  As I mentioned above, the alignments in `tmp_tele.bam` are exactly as they appear in the original BAM - MAPQ and flags are those that were reported by the aligner. `updated.bam` contains all the alignments in `tmp_tele.bam` but MAPQ is updated to reflect the final assignment probabilities, the primary read is the "reassigned" location and others are marked as secondary. Tags are added as described in the documentation, including the posterior probability.

Finally, the updated BAM functionality is a direct carry-over from Telescope. Currently, UMI duplicate information is not being reported. We anticipate some improvements, such as removing secondary reads, etc. in a future release. Would be interested to hear about how you intend to use the updated BAM.

**Comment by mlbendall** [comment]
@fansalon I am trying to figure out where in the documentation you got the reversed explanation (so we can fix it) can you please let me know?

**Comment by fansalon** [comment]
Hi Matthew,

the reversed explanation is in the protocol documentation (https://github.com/nixonlab/stellarscope/blob/main/docs/protocol.md) under the "**Basic Stellarscope analysis**" section, the paragraph just before the section "**Advanced Stellarscope analysis: multiple pooling modes**".

Thanks also for the explanation about the BAM files. The reason why I was asking this is merely practical - since I am running stellarscope on a large dataset  I am in need to save disk space and wanted to delete the files I think I won't use in the future. But I still wanted to keep the "final" BAM file used to get the TE counts. And this gets to your question ("Would be interested to hear about how you intend to use the updated BAM.") Overall, I think it is great to output the BAM files internally used to generate the TE counts as the user can traceback the alignments of some loci of interest, visualize them (*e.g.*, IGV), double-check them, etc - all manual work that I usually do on some selected loci of interest. 

Thanks for making the BAM available, I implemented the same in the tool I developed in the past to quantify TE expression from bulk RNAseq - https://github.com/fansalon/TEspeX, but I noticed it is not alway common praxis.

All the best,
Federico
